In [1]:
import plotly.offline as pyo
import plotly.graph_objs as go 
import pandas as pd

In [2]:
df = pd.read_csv('nst-est2017-alldata.csv')

In [3]:
df2 = df[df['DIVISION']=='1']
df2.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2015,RDOMESTICMIG2016,RDOMESTICMIG2017,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017
11,40.0,1,1,9.0,Connecticut,3574097.0,3574114.0,3580171.0,3591927.0,3597705.0,...,-8.376089,-8.106331,-6.206914,0.993851,-0.542726,-0.420268,-2.479362,-3.464252,-3.112421,-1.257548
24,40.0,1,1,23.0,Maine,1328361.0,1328362.0,1327568.0,1327968.0,1328101.0,...,-0.781424,1.807361,4.032798,0.685361,0.178459,0.392308,1.301528,0.389959,3.000731,5.216532
26,40.0,1,1,25.0,Massachusetts,6547629.0,6547808.0,6564943.0,6612178.0,6659627.0,...,-3.270088,-4.423353,-3.374712,4.364383,4.266338,5.211370,4.538697,3.276287,2.261905,3.246090
34,40.0,1,1,33.0,New Hampshire,1316470.0,1316460.0,1316700.0,1318345.0,1320923.0,...,-0.850002,1.333509,3.500622,-0.403029,0.632751,0.061281,3.793602,0.852258,3.037729,5.170643
44,40.0,1,1,44.0,Rhode Island,1052567.0,1052945.0,1053169.0,1052154.0,1052761.0,...,-4.218510,-4.093718,-3.640649,-2.170688,-0.991964,-1.139847,1.029624,0.368598,0.526146,0.891742

In [4]:
df2.set_index('NAME', inplace=True )

In [5]:
list_of_pop_col = [col for col in df2.columns if col.startswith('POP')]

In [6]:
list_of_pop_col

['POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'POPESTIMATE2016',
 'POPESTIMATE2017']

In [8]:
df2 = df2[list_of_pop_col]
df2

,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017
NAME,,,,,,,,
Connecticut,3580171.0,3591927.0,3597705.0,3602470.0,3600188.0,3593862.0,3587685.0,3588184.0
Maine,1327568.0,1327968.0,1328101.0,1327975.0,1328903.0,1327787.0,1330232.0,1335907.0
Massachusetts,6564943.0,6612178.0,6659627.0,6711138.0,6757925.0,6794002.0,6823721.0,6859819.0
New Hampshire,1316700.0,1318345.0,1320923.0,1322622.0,1328684.0,1330134.0,1335015.0,1342795.0
Rhode Island,1053169.0,1052154.0,1052761.0,1052784.0,1054782.0,1055916.0,1057566.0,1059639.0
Vermont,625842.0,626210.0,625606.0,626044.0,625665.0,624455.0,623354.0,623657.0